// lib/products.ts — Complete product catalog with verified images & daily-use essentials

import { getProductImage as resolveProductImage } from "@/lib/getProductImage";
import { getProductImageByName } from "@/lib/productImages";

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  mrp: number;
  size: string;
  deliveryTime: string;
  image: string;
  // Optional admin image metadata retained for future Cloudinary/DB workflows.
  /** Admin-uploaded Cloudinary URL — highest priority */
  customImage?: string;
  /** Pre-verified Open Food Facts CDN URL — second priority */
  offImageUrl?: string;
  /** EAN-13 barcode for live OFF API lookup — third priority */
  barcode?: string;
  badge?: "Best Seller" | "New" | "Popular" | "Fresh Today" | "Organic";
  rating: number;
  reviews: number;
  inStock: boolean;
}

export const CATEGORIES = [
  { id: "all", label: "All Products", icon: "🛒" },
  { id: "rice-grains", label: "Rice & Grains", icon: "🌾" },
  { id: "dals-pulses", label: "Dals & Pulses", icon: "🫘" },
  { id: "edible-oils", label: "Edible Oils", icon: "🫙" },
  { id: "spices", label: "Spices & Masala", icon: "🌶️" },
  { id: "snacks", label: "Snacks", icon: "🍿" },
  { id: "beverages", label: "Beverages", icon: "☕" },
  { id: "household", label: "Household", icon: "🧹" },
  { id: "personal-care", label: "Personal Care", icon: "🧴" },
  { id: "dairy", label: "Dairy & Eggs", icon: "🥛" },
  { id: "bakery", label: "Bakery & Bread", icon: "🍞" },
  { id: "millets", label: "Millets & Health", icon: "✨" },
  { id: "sugar-salt", label: "Sugar, Salt & More", icon: "🧂" },
];


export const PRODUCTS: Product[] = [
  // ─── Rice & Grains ────────────────────────────────────────────────────────
  {
    id: "rice-1",
    name: "Kalyani Premium Sona Masoori",
    brand: "Kalyani",
    category: "rice-grains",
    price: 1199,
    mrp: 1499,
    size: "26 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Kalyani Premium Sona Masoori"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/404/550/0033/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.8,
    reviews: 2341,
    inStock: true,
  },
  {
    id: "rice-2",
    name: "India Gate Basmati Rice",
    brand: "India Gate",
    category: "rice-grains",
    price: 399,
    mrp: 449,
    size: "5 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("India Gate Basmati Rice"),
    barcode: "8901030756680",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/075/6680/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.7,
    reviews: 9876,
    inStock: true,
  },
  {
    id: "rice-6",
    name: "Fortune Chakki Atta",
    brand: "Fortune",
    category: "rice-grains",
    price: 249,
    mrp: 285,
    size: "5 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Fortune Chakki Atta"),
    barcode: "8901267012302",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/126/701/2302/front_en.3.400.jpg",
    rating: 4.5,
    reviews: 4830,
    inStock: true,
  },
  {
    id: "rice-3",
    name: "Aashirvaad Whole Wheat Atta",
    brand: "Aashirvaad",
    category: "rice-grains",
    price: 265,
    mrp: 299,
    size: "5 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Aashirvaad Whole Wheat Atta"),
    barcode: "8901030753474",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/075/3474/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.7,
    reviews: 5102,
    inStock: true,
  },
  {
    id: "rice-4",
    name: "Pillsbury Maida",
    brand: "Pillsbury",
    category: "rice-grains",
    price: 55,
    mrp: 65,
    size: "1 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Pillsbury Maida"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/126/701/2401/front_en.3.400.jpg",
    rating: 4.4,
    reviews: 3201,
    inStock: true,
  },
  {
    id: "rice-5",
    name: "Besan (Gram Flour)",
    brand: "Rajdhani",
    category: "rice-grains",
    price: 72,
    mrp: 89,
    size: "1 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Besan (Gram Flour)"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/075/6130/front_en.3.400.jpg",
    badge: "New",
    rating: 4.5,
    reviews: 1204,
    inStock: true,
  },

  // ─── Dals & Pulses ───────────────────────────────────────────────────────
  {
    id: "dal-1",
    name: "Toor Dal Premium",
    brand: "Organic India",
    category: "dals-pulses",
    price: 129,
    mrp: 149,
    size: "1 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Toor Dal Premium"),
    barcode: "8904109421412",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/410/942/1412/front_en.3.400.jpg",
    rating: 4.4,
    reviews: 1203,
    inStock: true,
  },
  {
    id: "dal-2",
    name: "Yellow Moong Dal",
    brand: "24 Mantra Organic",
    category: "dals-pulses",
    price: 89,
    mrp: 109,
    size: "500 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Yellow Moong Dal"),
    barcode: "8906050070044",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/605/007/0044/front_en.3.400.jpg",
    badge: "Organic",
    rating: 4.6,
    reviews: 782,
    inStock: true,
  },
  {
    id: "dal-3",
    name: "Masoor Dal (Red Lentils)",
    brand: "Fortune",
    category: "dals-pulses",
    price: 95,
    mrp: 115,
    size: "1 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Masoor Dal (Red Lentils)"),
    barcode: "8906050070051",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/605/007/0051/front_en.3.400.jpg",
    rating: 4.3,
    reviews: 654,
    inStock: true,
  },
  {
    id: "dal-4",
    name: "Chana Dal",
    brand: "Patanjali",
    category: "dals-pulses",
    price: 82,
    mrp: 99,
    size: "1 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Chana Dal"),
    barcode: "8906002420017",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/600/242/0017/front_en.3.400.jpg",
    rating: 4.2,
    reviews: 901,
    inStock: true,
  },
  {
    id: "dal-5",
    name: "Rajma (Kidney Beans)",
    brand: "Organic India",
    category: "dals-pulses",
    price: 110,
    mrp: 130,
    size: "500 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Rajma (Kidney Beans)"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/605/007/0082/front_en.3.400.jpg",
    badge: "Organic",
    rating: 4.5,
    reviews: 543,
    inStock: true,
  },
  {
    id: "dal-6",
    name: "Urad Dal White",
    brand: "24 Mantra Organic",
    category: "dals-pulses",
    price: 99,
    mrp: 119,
    size: "500 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Urad Dal White"),
    barcode: "8906050070068",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/605/007/0068/front_en.3.400.jpg",
    badge: "Organic",
    rating: 4.4,
    reviews: 621,
    inStock: true,
  },

  // ─── Edible Oils ─────────────────────────────────────────────────────────
  {
    id: "oil-1",
    name: "Fortune Sunflower Oil",
    brand: "Fortune",
    category: "edible-oils",
    price: 629,
    mrp: 699,
    size: "5 L",
    deliveryTime: "30 min",
    image: getProductImageByName("Fortune Sunflower Oil"),
    barcode: "8901267023636",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/126/702/3636/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.5,
    reviews: 3201,
    inStock: true,
  },
  {
    id: "oil-2",
    name: "Saffola Active Oil",
    brand: "Saffola",
    category: "edible-oils",
    price: 189,
    mrp: 219,
    size: "1 L",
    deliveryTime: "30 min",
    image: getProductImageByName("Saffola Active Oil"),
    barcode: "8901030014276",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/001/4276/front_en.3.400.jpg",
    rating: 4.3,
    reviews: 1540,
    inStock: true,
  },
  {
    id: "oil-3",
    name: "Dhara Mustard Oil",
    brand: "Dhara",
    category: "edible-oils",
    price: 149,
    mrp: 175,
    size: "1 L",
    deliveryTime: "30 min",
    image: getProductImageByName("Dhara Mustard Oil"),
    barcode: "8901267012036",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/126/701/2036/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.4,
    reviews: 2180,
    inStock: true,
  },
  {
    id: "oil-4",
    name: "Parachute Coconut Oil",
    brand: "Parachute",
    category: "edible-oils",
    price: 110,
    mrp: 130,
    size: "500 mL",
    deliveryTime: "30 min",
    image: getProductImageByName("Parachute Coconut Oil"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/001/2913/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.6,
    reviews: 4320,
    inStock: true,
  },
  {
    id: "oil-5",
    name: "Patanjali Cow Ghee",
    brand: "Patanjali",
    category: "edible-oils",
    price: 499,
    mrp: 560,
    size: "500 mL",
    deliveryTime: "30 min",
    image: getProductImageByName("Patanjali Cow Ghee"),
    barcode: "8904109401408",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/410/940/1408/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.7,
    reviews: 5820,
    inStock: true,
  },

  // ─── Spices & Masala ──────────────────────────────────────────────────────
  {
    id: "spice-1",
    name: "MDH Chana Masala",
    brand: "MDH",
    category: "spices",
    price: 55,
    mrp: 65,
    size: "100 g",
    deliveryTime: "30 min",
    image: getProductImageByName("MDH Chana Masala"),
    barcode: "8901058000106",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/105/800/0106/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.7,
    reviews: 6201,
    inStock: true,
  },
  {
    id: "spice-2",
    name: "Everest Garam Masala",
    brand: "Everest",
    category: "spices",
    price: 45,
    mrp: 55,
    size: "100 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Everest Garam Masala"),
    barcode: "8904030000012",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/403/000/0012/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.6,
    reviews: 5410,
    inStock: true,
  },
  {
    id: "spice-7",
    name: "MDH Chunky Chat Masala",
    brand: "MDH",
    category: "spices",
    price: 48,
    mrp: 58,
    size: "100 g",
    deliveryTime: "30 min",
    image: getProductImageByName("MDH Chunky Chat Masala"),
    barcode: "8901058900024",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/105/890/0024/front_en.3.400.jpg",
    rating: 4.5,
    reviews: 3102,
    inStock: true,
  },
  {
    id: "spice-8",
    name: "Catch Black Pepper Powder",
    brand: "Catch",
    category: "spices",
    price: 55,
    mrp: 68,
    size: "50 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Catch Black Pepper Powder"),
    barcode: "8901998011094",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/199/801/1094/front_en.3.400.jpg",
    rating: 4.4,
    reviews: 1820,
    inStock: true,
  },
  {
    id: "spice-3",
    name: "Turmeric Powder (Haldi)",
    brand: "Catch",
    category: "spices",
    price: 38,
    mrp: 45,
    size: "200 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Turmeric Powder (Haldi)"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/199/801/1049/front_en.3.400.jpg",
    badge: "Organic",
    rating: 4.5,
    reviews: 3821,
    inStock: true,
  },
  {
    id: "spice-4",
    name: "Red Chilli Powder",
    brand: "Everest",
    category: "spices",
    price: 42,
    mrp: 51,
    size: "200 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Red Chilli Powder"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/403/000/0012/front_en.3.400.jpg",
    rating: 4.4,
    reviews: 2905,
    inStock: true,
  },
  {
    id: "spice-5",
    name: "Coriander Powder (Dhania)",
    brand: "MDH",
    category: "spices",
    price: 35,
    mrp: 42,
    size: "100 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Coriander Powder (Dhania)"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/105/800/0113/front_en.3.400.jpg",
    rating: 4.3,
    reviews: 1823,
    inStock: true,
  },
  {
    id: "spice-6",
    name: "Cumin Seeds (Jeera)",
    brand: "Catch",
    category: "spices",
    price: 65,
    mrp: 78,
    size: "100 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Cumin Seeds (Jeera)"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/199/801/1056/front_en.3.400.jpg",
    badge: "New",
    rating: 4.5,
    reviews: 1102,
    inStock: true,
  },

  // ─── Snacks ───────────────────────────────────────────────────────────────
  {
    id: "snack-1",
    name: "Haldiram's Aloo Bhujia",
    brand: "Haldiram's",
    category: "snacks",
    price: 85,
    mrp: 99,
    size: "200 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Haldiram's Aloo Bhujia"),
    barcode: "8906002350023",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/600/235/0023/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.7,
    reviews: 8912,
    inStock: true,
  },
  {
    id: "snack-2",
    name: "Maggi 2-Minute Noodles",
    brand: "Maggi",
    category: "snacks",
    price: 60,
    mrp: 68,
    size: "4×70 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Maggi 2-Minute Noodles"),
    barcode: "8901058850015",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/105/885/0015/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.6,
    reviews: 12403,
    inStock: true,
  },
  {
    id: "snack-3",
    name: "Lay's Classic Salted Chips",
    brand: "Lay's",
    category: "snacks",
    price: 20,
    mrp: 20,
    size: "26 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Lay's Classic Salted Chips"),
    barcode: "8901491101091",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/149/110/1091/front_en.3.400.jpg",
    rating: 4.5,
    reviews: 14201,
    inStock: true,
  },
  {
    id: "snack-4",
    name: "Britannia Good Day Biscuits",
    brand: "Britannia",
    category: "snacks",
    price: 30,
    mrp: 35,
    size: "120 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Britannia Good Day Biscuits"),
    barcode: "8901063051040",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/305/1040/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.6,
    reviews: 9320,
    inStock: true,
  },
  {
    id: "snack-5",
    name: "Parle-G Original Biscuits",
    brand: "Parle",
    category: "snacks",
    price: 10,
    mrp: 10,
    size: "100 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Parle-G Original Biscuits"),
    barcode: "8901719110085",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/171/911/0085/front_en.5.400.jpg",
    badge: "Best Seller",
    rating: 4.8,
    reviews: 21034,
    inStock: true,
  },
  {
    id: "snack-6",
    name: "Britannia Marie Gold",
    brand: "Britannia",
    category: "snacks",
    price: 25,
    mrp: 30,
    size: "250 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Britannia Marie Gold"),
    barcode: "8901063710126",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/371/0126/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.5,
    reviews: 7320,
    inStock: true,
  },
  {
    id: "snack-7",
    name: "Sunfeast Dark Fantasy Choco",
    brand: "ITC",
    category: "snacks",
    price: 60,
    mrp: 70,
    size: "75 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Sunfeast Dark Fantasy Choco"),
    barcode: "8901030804533",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/080/4533/front_en.3.400.jpg",
    badge: "New",
    rating: 4.6,
    reviews: 4120,
    inStock: true,
  },
  {
    id: "snack-8",
    name: "Haldiram's Mixture",
    brand: "Haldiram's",
    category: "snacks",
    price: 75,
    mrp: 90,
    size: "200 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Haldiram's Mixture"),
    barcode: "8906002350047",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/600/235/0047/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.5,
    reviews: 3820,
    inStock: true,
  },
  {
    id: "snack-9",
    name: "Kurkure Masala Munch",
    brand: "Kurkure",
    category: "snacks",
    price: 20,
    mrp: 20,
    size: "73 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Kurkure Masala Munch"),
    barcode: "8901491106003",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/149/110/6003/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.4,
    reviews: 9810,
    inStock: true,
  },
  {
    id: "snack-10",
    name: "Hide & Seek Chocolate Chip",
    brand: "Parle",
    category: "snacks",
    price: 30,
    mrp: 35,
    size: "112 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Hide & Seek Chocolate Chip"),
    barcode: "8901063027002",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/302/7002/front_en.3.400.jpg",
    badge: "New",
    rating: 4.5,
    reviews: 2940,
    inStock: true,
  },

  // ─── Beverages ────────────────────────────────────────────────────────────
  {
    id: "bev-1",
    name: "BRU Super Strong Coffee",
    brand: "BRU",
    category: "beverages",
    price: 225,
    mrp: 250,
    size: "200 g",
    deliveryTime: "30 min",
    image: getProductImageByName("BRU Super Strong Coffee"),
    barcode: "8901063104017",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/310/4017/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.5,
    reviews: 4301,
    inStock: true,
  },
  {
    id: "bev-2",
    name: "Tata Tea Premium",
    brand: "Tata",
    category: "beverages",
    price: 115,
    mrp: 135,
    size: "250 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Tata Tea Premium"),
    barcode: "8901584006203",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/158/400/6203/front_en.3.400.jpg",
    rating: 4.4,
    reviews: 6782,
    inStock: true,
  },
  {
    id: "bev-3",
    name: "Nescafe Sunrise",
    brand: "Nescafe",
    category: "beverages",
    price: 199,
    mrp: 229,
    size: "100 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Nescafe Sunrise"),
    barcode: "7613035352681",
    offImageUrl: "https://images.openfoodfacts.org/images/products/761/303/535/2681/front_en.5.400.jpg",
    rating: 4.6,
    reviews: 5901,
    inStock: true,
  },
  {
    id: "bev-4",
    name: "Horlicks Original",
    brand: "Horlicks",
    category: "beverages",
    price: 299,
    mrp: 349,
    size: "500 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Horlicks Original"),
    barcode: "8901063750016",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/375/0016/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.5,
    reviews: 3042,
    inStock: true,
  },
  {
    id: "bev-5",
    name: "Real Fruit Juice – Mango",
    brand: "Real",
    category: "beverages",
    price: 99,
    mrp: 115,
    size: "1 L",
    deliveryTime: "30 min",
    image: getProductImageByName("Real Fruit Juice – Mango"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/120/700/0352/front_en.3.400.jpg",
    badge: "New",
    rating: 4.3,
    reviews: 1823,
    inStock: true,
  },
  {
    id: "bev-6",
    name: "Red Label Natural Care Tea",
    brand: "Brooke Bond",
    category: "beverages",
    price: 248,
    mrp: 285,
    size: "500 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Red Label Natural Care Tea"),
    barcode: "8901030757007",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/075/7007/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.6,
    reviews: 8903,
    inStock: true,
  },
  {
    id: "bev-7",
    name: "Bournvita Health Drink",
    brand: "Cadbury",
    category: "beverages",
    price: 349,
    mrp: 399,
    size: "500 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Bournvita Health Drink"),
    barcode: "8901063750016",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/375/0016/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.7,
    reviews: 12480,
    inStock: true,
  },
  {
    id: "bev-8",
    name: "Horlicks Classic Malt",
    brand: "Horlicks",
    category: "beverages",
    price: 295,
    mrp: 340,
    size: "500 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Horlicks Classic Malt"),
    barcode: "8901030012913",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/001/2913/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.5,
    reviews: 5640,
    inStock: true,
  },
  {
    id: "bev-9",
    name: "Complan Chocolate",
    brand: "Complan",
    category: "beverages",
    price: 289,
    mrp: 325,
    size: "500 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Complan Chocolate"),
    barcode: "8901058854518",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/105/885/4518/front_en.3.400.jpg",
    rating: 4.4,
    reviews: 3210,
    inStock: true,
  },

  // ─── Household ────────────────────────────────────────────────────────────
  {
    id: "house-1",
    name: "Surf Excel Matic Liquid",
    brand: "Surf Excel",
    category: "household",
    price: 199,
    mrp: 239,
    size: "1 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Surf Excel Matic Liquid"),
    barcode: "8901030756000",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/075/6000/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.5,
    reviews: 7203,
    inStock: true,
  },
  {
    id: "house-2",
    name: "Harpic Power Plus",
    brand: "Harpic",
    category: "household",
    price: 155,
    mrp: 175,
    size: "750 mL",
    deliveryTime: "30 min",
    image: getProductImageByName("Harpic Power Plus"),
    barcode: "8901396111145",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/139/611/1145/front_en.3.400.jpg",
    rating: 4.3,
    reviews: 3102,
    inStock: true,
  },
  {
    id: "house-3",
    name: "Vim Dishwash Bar",
    brand: "Vim",
    category: "household",
    price: 42,
    mrp: 50,
    size: "200 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Vim Dishwash Bar"),
    barcode: "8901030756130",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/075/6130/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.4,
    reviews: 5610,
    inStock: true,
  },
  {
    id: "house-4",
    name: "Colin Glass Cleaner",
    brand: "Colin",
    category: "household",
    price: 89,
    mrp: 105,
    size: "500 mL",
    deliveryTime: "30 min",
    image: getProductImageByName("Colin Glass Cleaner"),
    barcode: "8901396102952",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/139/610/2952/front_en.3.400.jpg",
    rating: 4.2,
    reviews: 1820,
    inStock: true,
  },
  {
    id: "house-5",
    name: "Good Knight Mosquito Coil",
    brand: "Good Knight",
    category: "household",
    price: 49,
    mrp: 60,
    size: "10 pcs",
    deliveryTime: "30 min",
    image: getProductImageByName("Good Knight Mosquito Coil"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/139/611/1145/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.3,
    reviews: 2210,
    inStock: true,
  },
  {
    id: "house-6",
    name: "Scotch-Brite Scrub Pad",
    brand: "Scotch-Brite",
    category: "household",
    price: 35,
    mrp: 45,
    size: "3 pcs",
    deliveryTime: "30 min",
    image: getProductImageByName("Scotch-Brite Scrub Pad"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/075/6000/front_en.3.400.jpg",
    rating: 4.5,
    reviews: 4102,
    inStock: true,
  },
  {
    id: "house-7",
    name: "Ariel Matic Front Load",
    brand: "Ariel",
    category: "household",
    price: 249,
    mrp: 299,
    size: "1 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Ariel Matic Front Load"),
    barcode: "8001841499322",
    offImageUrl: "https://images.openfoodfacts.org/images/products/800/184/149/9322/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.5,
    reviews: 6140,
    inStock: true,
  },
  {
    id: "house-8",
    name: "Lizol Citrus Floor Cleaner",
    brand: "Lizol",
    category: "household",
    price: 139,
    mrp: 165,
    size: "975 mL",
    deliveryTime: "30 min",
    image: getProductImageByName("Lizol Citrus Floor Cleaner"),
    barcode: "8901396107285",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/139/610/7285/front_en.3.400.jpg",
    rating: 4.3,
    reviews: 3890,
    inStock: true,
  },
  {
    id: "house-9",
    name: "Comfort Fabric Conditioner",
    brand: "Comfort",
    category: "household",
    price: 159,
    mrp: 199,
    size: "860 mL",
    deliveryTime: "30 min",
    image: getProductImageByName("Comfort Fabric Conditioner"),
    barcode: "8901030754174",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/075/4174/front_en.3.400.jpg",
    badge: "New",
    rating: 4.4,
    reviews: 2150,
    inStock: true,
  },

  // ─── Personal Care ────────────────────────────────────────────────────────
  {
    id: "care-1",
    name: "Colgate MaxFresh Toothpaste",
    brand: "Colgate",
    category: "personal-care",
    price: 75,
    mrp: 89,
    size: "150 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Colgate MaxFresh Toothpaste"),
    barcode: "8901314005872",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/131/400/5872/front_en.3.400.jpg",
    rating: 4.5,
    reviews: 9301,
    inStock: true,
  },
  {
    id: "care-2",
    name: "Dove Body Wash",
    brand: "Dove",
    category: "personal-care",
    price: 179,
    mrp: 225,
    size: "200 mL",
    deliveryTime: "30 min",
    image: getProductImageByName("Dove Body Wash"),
    barcode: "8901030743291",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/074/3291/front_en.3.400.jpg",
    badge: "New",
    rating: 4.7,
    reviews: 2801,
    inStock: true,
  },
  {
    id: "care-3",
    name: "Head & Shoulders Shampoo",
    brand: "Head & Shoulders",
    category: "personal-care",
    price: 165,
    mrp: 199,
    size: "340 mL",
    deliveryTime: "30 min",
    image: getProductImageByName("Head & Shoulders Shampoo"),
    barcode: "8001841446455",
    offImageUrl: "https://images.openfoodfacts.org/images/products/800/184/144/6455/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.5,
    reviews: 6320,
    inStock: true,
  },
  {
    id: "care-4",
    name: "Dettol Antiseptic Liquid",
    brand: "Dettol",
    category: "personal-care",
    price: 105,
    mrp: 130,
    size: "250 mL",
    deliveryTime: "30 min",
    image: getProductImageByName("Dettol Antiseptic Liquid"),
    barcode: "8901396013207",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/139/601/3207/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.6,
    reviews: 11203,
    inStock: true,
  },
  {
    id: "care-5",
    name: "Himalaya Face Wash Neem",
    brand: "Himalaya",
    category: "personal-care",
    price: 140,
    mrp: 169,
    size: "100 mL",
    deliveryTime: "30 min",
    image: getProductImageByName("Himalaya Face Wash Neem"),
    barcode: "8901138503979",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/113/850/3979/front_en.3.400.jpg",
    badge: "New",
    rating: 4.4,
    reviews: 3201,
    inStock: true,
  },
  {
    id: "care-6",
    name: "Whisper Ultra Pads",
    brand: "Whisper",
    category: "personal-care",
    price: 82,
    mrp: 99,
    size: "15 pcs",
    deliveryTime: "30 min",
    image: getProductImageByName("Whisper Ultra Pads"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/139/601/3207/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.6,
    reviews: 7820,
    inStock: true,
  },
  {
    id: "care-7",
    name: "Gillette Mach3 Razor",
    brand: "Gillette",
    category: "personal-care",
    price: 199,
    mrp: 249,
    size: "1 pc",
    deliveryTime: "30 min",
    image: getProductImageByName("Gillette Mach3 Razor"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/131/400/5872/front_en.3.400.jpg",
    rating: 4.5,
    reviews: 4102,
    inStock: true,
  },
  {
    id: "care-8",
    name: "Vaseline Petroleum Jelly",
    brand: "Vaseline",
    category: "personal-care",
    price: 78,
    mrp: 92,
    size: "250 mL",
    deliveryTime: "30 min",
    image: getProductImageByName("Vaseline Petroleum Jelly"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/074/3291/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.7,
    reviews: 8901,
    inStock: true,
  },
  {
    id: "care-9",
    name: "Colgate Strong Teeth",
    brand: "Colgate",
    category: "personal-care",
    price: 55,
    mrp: 68,
    size: "200 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Colgate Strong Teeth"),
    barcode: "8901314004127",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/131/400/4127/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.4,
    reviews: 7820,
    inStock: true,
  },
  {
    id: "care-10",
    name: "Lifebuoy Total Soap",
    brand: "Lifebuoy",
    category: "personal-care",
    price: 38,
    mrp: 45,
    size: "125 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Lifebuoy Total Soap"),
    barcode: "8901030004177",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/000/4177/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.5,
    reviews: 14302,
    inStock: true,
  },
  {
    id: "care-11",
    name: "Lux Soft Touch Soap",
    brand: "Lux",
    category: "personal-care",
    price: 40,
    mrp: 50,
    size: "125 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Lux Soft Touch Soap"),
    barcode: "8901030760144",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/076/0144/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.4,
    reviews: 9310,
    inStock: true,
  },
  {
    id: "care-12",
    name: "Pantene Silky Smooth Shampoo",
    brand: "Pantene",
    category: "personal-care",
    price: 155,
    mrp: 185,
    size: "340 mL",
    deliveryTime: "30 min",
    image: getProductImageByName("Pantene Silky Smooth Shampoo"),
    barcode: "8001841317335",
    offImageUrl: "https://images.openfoodfacts.org/images/products/800/184/131/7335/front_en.3.400.jpg",
    badge: "New",
    rating: 4.5,
    reviews: 5120,
    inStock: true,
  },

  // ─── Dairy & Eggs ────────────────────────────────────────────────────────
  {
    id: "dairy-1",
    name: "Amul Gold Full Cream Milk",
    brand: "Amul",
    category: "dairy",
    price: 28,
    mrp: 28,
    size: "500 mL",
    deliveryTime: "By 7AM",
    image: getProductImageByName("Amul Gold Full Cream Milk"),
    barcode: "8901063012104",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/301/2104/front_en.3.400.jpg",
    badge: "Fresh Today",
    rating: 4.6,
    reviews: 15203,
    inStock: true,
  },
  {
    id: "dairy-2",
    name: "Farm Fresh Eggs",
    brand: "Country Fresh",
    category: "dairy",
    price: 89,
    mrp: 99,
    size: "12 pcs",
    deliveryTime: "By 7AM",
    image: getProductImageByName("Farm Fresh Eggs"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/301/2104/front_en.3.400.jpg",
    badge: "Fresh Today",
    rating: 4.5,
    reviews: 6012,
    inStock: true,
  },
  {
    id: "dairy-3",
    name: "Amul Butter Salted",
    brand: "Amul",
    category: "dairy",
    price: 55,
    mrp: 58,
    size: "100 g",
    deliveryTime: "By 7AM",
    image: getProductImageByName("Amul Butter Salted"),
    barcode: "8901063000101",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/300/0101/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.7,
    reviews: 18201,
    inStock: true,
  },
  {
    id: "dairy-4",
    name: "Mother Dairy Fresh Paneer",
    brand: "Mother Dairy",
    category: "dairy",
    price: 80,
    mrp: 90,
    size: "200 g",
    deliveryTime: "By 7AM",
    image: getProductImageByName("Mother Dairy Fresh Paneer"),
    barcode: "8906019700029",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/601/970/0029/front_en.3.400.jpg",
    badge: "Fresh Today",
    rating: 4.5,
    reviews: 5320,
    inStock: true,
  },
  {
    id: "dairy-6",
    name: "Amul Taaza Toned Milk",
    brand: "Amul",
    category: "dairy",
    price: 24,
    mrp: 24,
    size: "500 mL",
    deliveryTime: "By 7AM",
    image: getProductImageByName("Amul Taaza Toned Milk"),
    barcode: "8901063012036",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/301/2036/front_en.3.400.jpg",
    badge: "Fresh Today",
    rating: 4.5,
    reviews: 9820,
    inStock: true,
  },
  {
    id: "dairy-7",
    name: "Amul Cheese Slices",
    brand: "Amul",
    category: "dairy",
    price: 115,
    mrp: 130,
    size: "200 g",
    deliveryTime: "By 7AM",
    image: getProductImageByName("Amul Cheese Slices"),
    barcode: "8901063001740",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/300/1740/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.6,
    reviews: 6340,
    inStock: true,
  },
  {
    id: "dairy-5",
    name: "Epigamia Greek Yogurt",
    brand: "Epigamia",
    category: "dairy",
    price: 65,
    mrp: 75,
    size: "90 g",
    deliveryTime: "By 7AM",
    image: getProductImageByName("Epigamia Greek Yogurt"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/300/1740/front_en.3.400.jpg",
    badge: "New",
    rating: 4.4,
    reviews: 2301,
    inStock: true,
  },

  // ─── Bakery & Bread ──────────────────────────────────────────────────────
  {
    id: "bakery-1",
    name: "Harvest Gold Bread",
    brand: "Harvest Gold",
    category: "bakery",
    price: 45,
    mrp: 50,
    size: "400 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Harvest Gold Bread"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/301/2104/front_en.3.400.jpg",
    badge: "Fresh Today",
    rating: 4.4,
    reviews: 8901,
    inStock: true,
  },
  {
    id: "bakery-2",
    name: "Britannia Brown Bread",
    brand: "Britannia",
    category: "bakery",
    price: 48,
    mrp: 55,
    size: "400 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Britannia Brown Bread"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/371/0126/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.5,
    reviews: 6730,
    inStock: true,
  },
  {
    id: "bakery-3",
    name: "Cream Croissant",
    brand: "Monginis",
    category: "bakery",
    price: 40,
    mrp: 50,
    size: "60 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Cream Croissant"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/080/4533/front_en.3.400.jpg",
    badge: "New",
    rating: 4.3,
    reviews: 1204,
    inStock: true,
  },

  // ─── Sugar, Salt & Essentials ────────────────────────────────────────────
  {
    id: "ss-1",
    name: "Tata Salt Iodised",
    brand: "Tata",
    category: "sugar-salt",
    price: 35,
    mrp: 40,
    size: "1 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Tata Salt Iodised"),
    barcode: "8901063010100",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/301/0100/front_en.3.400.jpg",
    badge: "Best Seller",
    rating: 4.6,
    reviews: 7420,
    inStock: true,
  },
  {
    id: "ss-2",
    name: "Uttam Sugar",
    brand: "Uttam",
    category: "sugar-salt",
    price: 48,
    mrp: 55,
    size: "1 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Uttam Sugar"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/601/100/0002/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.4,
    reviews: 3801,
    inStock: true,
  },
  {
    id: "ss-3",
    name: "Kissan Mixed Fruit Jam",
    brand: "Kissan",
    category: "sugar-salt",
    price: 89,
    mrp: 105,
    size: "200 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Kissan Mixed Fruit Jam"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/106/305/1040/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.5,
    reviews: 4210,
    inStock: true,
  },
  {
    id: "ss-4",
    name: "Dabur Honey",
    brand: "Dabur",
    category: "sugar-salt",
    price: 155,
    mrp: 180,
    size: "250 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Dabur Honey"),
    barcode: "8901207000352",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/120/700/0352/front_en.11.400.jpg",
    badge: "Best Seller",
    rating: 4.7,
    reviews: 9801,
    inStock: true,
  },
  {
    id: "ss-5",
    name: "Heinz Tomato Ketchup",
    brand: "Heinz",
    category: "sugar-salt",
    price: 120,
    mrp: 145,
    size: "450 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Heinz Tomato Ketchup"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/103/075/6000/front_en.3.400.jpg",
    rating: 4.5,
    reviews: 6320,
    inStock: true,
  },

  // ─── Millets & Health ────────────────────────────────────────────────────
  {
    id: "millet-1",
    name: "Organic India Quinoa",
    brand: "Organic India",
    category: "millets",
    price: 219,
    mrp: 269,
    size: "500 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Organic India Quinoa"),
    barcode: "8906050070013",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/605/007/0013/front_en.3.400.jpg",
    badge: "Organic",
    rating: 4.6,
    reviews: 1802,
    inStock: true,
  },
  {
    id: "millet-2",
    name: "Foxtail Millet",
    brand: "Siridhanya",
    category: "millets",
    price: 74,
    mrp: 89,
    size: "500 g",
    deliveryTime: "30 min",
    image: getProductImageByName("Foxtail Millet"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/605/007/0013/front_en.3.400.jpg",
    rating: 4.4,
    reviews: 934,
    inStock: true,
  },
  {
    id: "millet-3",
    name: "Quaker Oats",
    brand: "Quaker",
    category: "millets",
    price: 160,
    mrp: 189,
    size: "1 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Quaker Oats"),
    barcode: "8901491200019",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/149/120/0019/front_en.3.400.jpg",
    badge: "Popular",
    rating: 4.6,
    reviews: 7280,
    inStock: true,
  },
  {
    id: "millet-5",
    name: "True Elements Rolled Oats",
    brand: "True Elements",
    category: "millets",
    price: 199,
    mrp: 249,
    size: "1 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("True Elements Rolled Oats"),
    barcode: "8906003950019",
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/600/395/0019/front_en.3.400.jpg",
    badge: "Organic",
    rating: 4.7,
    reviews: 4210,
    inStock: true,
  },
  {
    id: "millet-4",
    name: "Ragi (Finger Millet) Flour",
    brand: "Organic India",
    category: "millets",
    price: 90,
    mrp: 110,
    size: "1 kg",
    deliveryTime: "30 min",
    image: getProductImageByName("Ragi (Finger Millet) Flour"),
    offImageUrl: "https://images.openfoodfacts.org/images/products/890/605/007/0013/front_en.3.400.jpg",
    badge: "Organic",
    rating: 4.5,
    reviews: 2103,
    inStock: true,
  },
];

// ─── Helper functions ────────────────────────────────────────────────────────
export function getProductsByCategory(categoryId: string): Product[] {
  if (categoryId === "all") return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === categoryId);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getDiscountPercent(price: number, mrp: number): number {
  if (mrp <= price) return 0;
  return Math.round(((mrp - price) / mrp) * 100);
}

/**
 * Returns the static packaging image for a product, or the local grocery placeholder.
 */
export function getProductImage(product: Product): string {
  return resolveProductImage(product);
}
