// lib/products.ts
// Complete, scalable product dataset for Sao General Store

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  mrp: number;
  image: string;
  weight: string;
  delivery: string;
  rating: number;
  reviews: number;
  inStock?: boolean;
  badge?: "Best Seller" | "Popular" | "New" | "Organic" | "Fresh Today";
}

export const CATEGORIES = [
  { id: "atta-rice-dal", label: "Atta, Rice & Dal", icon: "🌾" },
  { id: "cooking-oil", label: "Cooking Oil", icon: "🫙" },
  { id: "ghee-dairy", label: "Ghee & Dairy", icon: "🥛" },
  { id: "masala-spices", label: "Masala & Spices", icon: "🌶️" },
  { id: "dairy-breakfast", label: "Dairy & Breakfast", icon: "🥣" },
  { id: "organic-health", label: "Organic & Health", icon: "🌿" },
  { id: "biscuits-cookies", label: "Biscuits & Cookies", icon: "🍪" },
  { id: "noodles-ready-to-eat", label: "Noodles & Ready-to-Eat", icon: "🍜" },
  { id: "chips-namkeen", label: "Chips & Namkeen", icon: "🍿" },
  { id: "tea-coffee", label: "Tea & Coffee", icon: "☕" },
  { id: "health-drinks", label: "Health Drinks", icon: "🥤" },
  { id: "oats-breakfast", label: "Oats & Breakfast", icon: "🌾" },
  { id: "home-cleaning", label: "Home Cleaning", icon: "🧹" },
  { id: "personal-care", label: "Personal Care", icon: "🧴" },
];

export const PRODUCTS: Product[] = [
  // ─── Atta, Rice & Dal (10 products) ───────────────────────────────────────
  {
    id: "ard-1",
    name: "Aashirvaad Superior MP Atta",
    brand: "Aashirvaad",
    category: "atta-rice-dal",
    price: 245,
    mrp: 290,
    image: "https://m.media-amazon.com/images/I/81xU2e8yJFL._SL1500_.jpg",
    weight: "5 kg",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 12450,
    badge: "Best Seller",
  },
  {
    id: "ard-2",
    name: "India Gate Basmati Rice, Premium",
    brand: "India Gate",
    category: "atta-rice-dal",
    price: 699,
    mrp: 850,
    image: "https://m.media-amazon.com/images/I/71YyM7yT-fL._SL1500_.jpg",
    weight: "5 kg",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 8320,
    badge: "Popular",
  },
  {
    id: "ard-3",
    name: "Daawat Rozana Gold Basmati Rice",
    brand: "Daawat",
    category: "atta-rice-dal",
    price: 345,
    mrp: 420,
    image: "https://m.media-amazon.com/images/I/81I-u8P2X6L._SL1500_.jpg",
    weight: "5 kg",
    delivery: "12-18 mins",
    rating: 4.4,
    reviews: 5120,
  },
  {
    id: "ard-4",
    name: "Tata Sampann Unpolished Toor Dal",
    brand: "Tata",
    category: "atta-rice-dal",
    price: 185,
    mrp: 210,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "1 kg",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 3200,
    badge: "Best Seller",
  },
  {
    id: "ard-5",
    name: "Fortune Chakki Fresh Atta",
    brand: "Fortune",
    category: "atta-rice-dal",
    price: 235,
    mrp: 275,
    image: "https://m.media-amazon.com/images/I/81VfS2u9LGL._SL1500_.jpg",
    weight: "5 kg",
    delivery: "10-15 mins",
    rating: 4.3,
    reviews: 4100,
  },
  {
    id: "ard-6",
    name: "Tata Sampann Moong Dal",
    brand: "Tata",
    category: "atta-rice-dal",
    price: 145,
    mrp: 165,
    image: "https://m.media-amazon.com/images/I/61H-6Xh8uXL._SL1500_.jpg",
    weight: "1 kg",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 2100,
  },
  {
    id: "ard-7",
    name: "India Gate Mogra Basmati Rice",
    brand: "India Gate",
    category: "atta-rice-dal",
    price: 495,
    mrp: 580,
    image: "https://m.media-amazon.com/images/I/71YyM7yT-fL._SL1500_.jpg",
    weight: "5 kg",
    delivery: "15-20 mins",
    rating: 4.2,
    reviews: 1800,
  },
  {
    id: "ard-8",
    name: "24 Mantra Organic Sonamasuri Rice",
    brand: "Organic India",
    category: "atta-rice-dal",
    price: 125,
    mrp: 150,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "1 kg",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 950,
    badge: "Organic",
  },
  {
    id: "ard-9",
    name: "Fortune Besan",
    brand: "Fortune",
    category: "atta-rice-dal",
    price: 75,
    mrp: 90,
    image: "https://m.media-amazon.com/images/I/81VfS2u9LGL._SL1500_.jpg",
    weight: "1 kg",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 2300,
  },
  {
    id: "ard-10",
    name: "Tata Sampann Chana Dal",
    brand: "Tata",
    category: "atta-rice-dal",
    price: 115,
    mrp: 130,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "1 kg",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 1500,
  },

  // ─── Cooking Oil (10 products) ─────────────────────────────────────────────
  {
    id: "oil-1",
    name: "Fortune Sunlite Refined Sunflower Oil",
    brand: "Fortune",
    category: "cooking-oil",
    price: 145,
    mrp: 175,
    image: "https://m.media-amazon.com/images/I/71o1p9fV1BL._SL1500_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 15000,
    badge: "Best Seller",
  },
  {
    id: "oil-2",
    name: "Saffola Gold Pro Healthy Edible Oil",
    brand: "Saffola",
    category: "cooking-oil",
    price: 185,
    mrp: 220,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 9200,
    badge: "Popular",
  },
  {
    id: "oil-3",
    name: "Dhara Kachchi Ghani Mustard Oil",
    brand: "Dhara",
    category: "cooking-oil",
    price: 155,
    mrp: 185,
    image: "https://m.media-amazon.com/images/I/61+t4bF6oIL._SL1000_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 6500,
  },
  {
    id: "oil-4",
    name: "Saffola Active Refined Rice Bran Oil",
    brand: "Saffola",
    category: "cooking-oil",
    price: 165,
    mrp: 195,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 4800,
  },
  {
    id: "oil-5",
    name: "Fortune Kachi Ghani Pure Mustard Oil",
    brand: "Fortune",
    category: "cooking-oil",
    price: 160,
    mrp: 190,
    image: "https://m.media-amazon.com/images/I/71o1p9fV1BL._SL1500_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 3900,
  },
  {
    id: "oil-6",
    name: "Dhara Refined Sunflower Oil",
    brand: "Dhara",
    category: "cooking-oil",
    price: 140,
    mrp: 165,
    image: "https://m.media-amazon.com/images/I/61+t4bF6oIL._SL1000_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.3,
    reviews: 2100,
  },
  {
    id: "oil-7",
    name: "Emami Healthy & Tasty Rice Bran Oil",
    brand: "Emami",
    category: "cooking-oil",
    price: 135,
    mrp: 160,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "1 L",
    delivery: "15-20 mins",
    rating: 4.2,
    reviews: 1200,
  },
  {
    id: "oil-8",
    name: "Gemini Refined Sunflower Oil",
    brand: "Gemini",
    category: "cooking-oil",
    price: 130,
    mrp: 155,
    image: "https://m.media-amazon.com/images/I/71o1p9fV1BL._SL1500_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.1,
    reviews: 800,
  },
  {
    id: "oil-9",
    name: "Saffola Total Pro Heart Oil",
    brand: "Saffola",
    category: "cooking-oil",
    price: 210,
    mrp: 250,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.8,
    reviews: 3500,
    badge: "Popular",
  },
  {
    id: "oil-10",
    name: "Fortune Refined Soyabean Oil",
    brand: "Fortune",
    category: "cooking-oil",
    price: 125,
    mrp: 150,
    image: "https://m.media-amazon.com/images/I/71o1p9fV1BL._SL1500_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 2900,
  },

  // ─── Ghee & Dairy (10 products) ───────────────────────────────────────────
  {
    id: "ghee-1",
    name: "Amul Pure Ghee, Tin",
    brand: "Amul",
    category: "ghee-dairy",
    price: 595,
    mrp: 650,
    image: "https://m.media-amazon.com/images/I/71YyM7yT-fL._SL1500_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 25000,
    badge: "Best Seller",
  },
  {
    id: "ghee-2",
    name: "Mother Dairy Cow Ghee",
    brand: "Mother Dairy",
    category: "ghee-dairy",
    price: 545,
    mrp: 600,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 12000,
    badge: "Popular",
  },
  {
    id: "ghee-3",
    name: "Britannia Cow Ghee",
    brand: "Britannia",
    category: "ghee-dairy",
    price: 525,
    mrp: 580,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 8000,
  },
  {
    id: "dairy-1",
    name: "Amul Butter (Salted)",
    brand: "Amul",
    category: "ghee-dairy",
    price: 52,
    mrp: 55,
    image: "https://m.media-amazon.com/images/I/71YyM7yT-fL._SL1500_.jpg",
    weight: "100 g",
    delivery: "8-12 mins",
    rating: 4.9,
    reviews: 45000,
    badge: "Best Seller",
  },
  {
    id: "dairy-2",
    name: "Britannia Cheese Slices",
    brand: "Britannia",
    category: "ghee-dairy",
    price: 145,
    mrp: 160,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "200 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 9500,
    badge: "Popular",
  },
  {
    id: "dairy-3",
    name: "Amul Cheese Cubes",
    brand: "Amul",
    category: "ghee-dairy",
    price: 120,
    mrp: 130,
    image: "https://m.media-amazon.com/images/I/71YyM7yT-fL._SL1500_.jpg",
    weight: "200 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 15000,
  },
  {
    id: "dairy-4",
    name: "Mother Dairy Paneer",
    brand: "Mother Dairy",
    category: "ghee-dairy",
    price: 85,
    mrp: 95,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "200 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 3200,
  },
  {
    id: "dairy-5",
    name: "Amul Kool Kesar Bottle",
    brand: "Amul",
    category: "ghee-dairy",
    price: 25,
    mrp: 25,
    image: "https://m.media-amazon.com/images/I/71YyM7yT-fL._SL1500_.jpg",
    weight: "180 ml",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 5000,
  },
  {
    id: "dairy-6",
    name: "Gowardhan Pure Cow Ghee",
    brand: "Gowardhan",
    category: "ghee-dairy",
    price: 575,
    mrp: 630,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 7000,
  },
  {
    id: "dairy-7",
    name: "Amul Malai Paneer",
    brand: "Amul",
    category: "ghee-dairy",
    price: 90,
    mrp: 100,
    image: "https://m.media-amazon.com/images/I/71YyM7yT-fL._SL1500_.jpg",
    weight: "200 g",
    delivery: "10-15 mins",
    rating: 4.8,
    reviews: 18000,
  },

  // ─── Masala & Spices (10 products) ─────────────────────────────────────────
  {
    id: "spice-1",
    name: "MDH Kitchen King Masala",
    brand: "MDH",
    category: "masala-spices",
    price: 78,
    mrp: 85,
    image: "https://m.media-amazon.com/images/I/81fI9mYp7OL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 12000,
    badge: "Best Seller",
  },
  {
    id: "spice-2",
    name: "Everest Garam Masala",
    brand: "Everest",
    category: "masala-spices",
    price: 65,
    mrp: 75,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 9500,
    badge: "Popular",
  },
  {
    id: "spice-3",
    name: "Catch Turmeric Powder",
    brand: "Catch",
    category: "masala-spices",
    price: 35,
    mrp: 45,
    image: "https://m.media-amazon.com/images/I/81fI9mYp7OL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 8000,
  },
  {
    id: "spice-4",
    name: "MDH Chana Masala",
    brand: "MDH",
    category: "masala-spices",
    price: 75,
    mrp: 82,
    image: "https://m.media-amazon.com/images/I/81fI9mYp7OL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 5000,
  },
  {
    id: "spice-5",
    name: "Everest Red Chilli Powder",
    brand: "Everest",
    category: "masala-spices",
    price: 45,
    mrp: 55,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 11000,
  },
  {
    id: "spice-6",
    name: "Catch Coriander Powder",
    brand: "Catch",
    category: "masala-spices",
    price: 38,
    mrp: 48,
    image: "https://m.media-amazon.com/images/I/81fI9mYp7OL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 4200,
  },
  {
    id: "spice-7",
    name: "Tata Sampann Turmeric Powder",
    brand: "Tata",
    category: "masala-spices",
    price: 42,
    mrp: 50,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 6300,
    badge: "Popular",
  },
  {
    id: "spice-8",
    name: "MDH Deggi Mirch",
    brand: "MDH",
    category: "masala-spices",
    price: 95,
    mrp: 105,
    image: "https://m.media-amazon.com/images/I/81fI9mYp7OL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.8,
    reviews: 7800,
  },
  {
    id: "spice-9",
    name: "Everest Chaat Masala",
    brand: "Everest",
    category: "masala-spices",
    price: 55,
    mrp: 65,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 5900,
  },
  {
    id: "spice-10",
    name: "Catch Black Pepper Powder",
    brand: "Catch",
    category: "masala-spices",
    price: 65,
    mrp: 78,
    image: "https://m.media-amazon.com/images/I/81fI9mYp7OL._SL1500_.jpg",
    weight: "50 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 3200,
  },

  // ─── Dairy & Breakfast (10 products) ───────────────────────────────────────
  {
    id: "db-1",
    name: "Kellogg's Corn Flakes",
    brand: "Kellogg's",
    category: "dairy-breakfast",
    price: 185,
    mrp: 210,
    image: "https://m.media-amazon.com/images/I/71+v9h1-E6L._SL1500_.jpg",
    weight: "475 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 21000,
    badge: "Best Seller",
  },
  {
    id: "db-2",
    name: "Quaker Oats",
    brand: "Quaker",
    category: "dairy-breakfast",
    price: 199,
    mrp: 230,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "1 kg",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 15000,
    badge: "Popular",
  },
  {
    id: "db-3",
    name: "Amul Masti Spiced Buttermilk",
    brand: "Amul",
    category: "dairy-breakfast",
    price: 15,
    mrp: 15,
    image: "https://m.media-amazon.com/images/I/71YyM7yT-fL._SL1500_.jpg",
    weight: "200 ml",
    delivery: "8-12 mins",
    rating: 4.8,
    reviews: 10000,
  },
  {
    id: "db-4",
    name: "Mother Dairy Fruit Yogurt",
    brand: "Mother Dairy",
    category: "dairy-breakfast",
    price: 30,
    mrp: 35,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 3200,
    badge: "New",
  },
  {
    id: "db-5",
    name: "Kellogg's Muesli",
    brand: "Kellogg's",
    category: "dairy-breakfast",
    price: 325,
    mrp: 375,
    image: "https://m.media-amazon.com/images/I/71+v9h1-E6L._SL1500_.jpg",
    weight: "500 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 8000,
  },
  {
    id: "db-6",
    name: "Amul Malai Paneer, Fresh",
    brand: "Amul",
    category: "dairy-breakfast",
    price: 90,
    mrp: 100,
    image: "https://m.media-amazon.com/images/I/71YyM7yT-fL._SL1500_.jpg",
    weight: "200 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 12000,
  },
  {
    id: "db-7",
    name: "Baggry's White Oats",
    brand: "Baggry's",
    category: "dairy-breakfast",
    price: 165,
    mrp: 195,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "1 kg",
    delivery: "10-15 mins",
    rating: 4.3,
    reviews: 2100,
  },
  {
    id: "db-8",
    name: "Tata Soulfull Ragi Bites",
    brand: "Tata",
    category: "dairy-breakfast",
    price: 145,
    mrp: 170,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "250 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 4500,
    badge: "Popular",
  },
  {
    id: "db-9",
    name: "Britannia Brown Bread",
    brand: "Britannia",
    category: "dairy-breakfast",
    price: 45,
    mrp: 50,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "400 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 6000,
  },
  {
    id: "db-10",
    name: "Amul Whipped Cream",
    brand: "Amul",
    category: "dairy-breakfast",
    price: 195,
    mrp: 220,
    image: "https://m.media-amazon.com/images/I/71YyM7yT-fL._SL1500_.jpg",
    weight: "250 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 1800,
  },

  // ─── Organic & Health (10 products) ────────────────────────────────────────
  {
    id: "oh-1",
    name: "Organic India Tulsi Green Tea",
    brand: "Organic India",
    category: "organic-health",
    price: 175,
    mrp: 199,
    image: "https://m.media-amazon.com/images/I/61+t4bF6oIL._SL1000_.jpg",
    weight: "25 Tea Bags",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 15000,
    badge: "Organic",
  },
  {
    id: "oh-2",
    name: "24 Mantra Organic Honey",
    brand: "Organic India",
    category: "organic-health",
    price: 245,
    mrp: 290,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "500 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 8200,
    badge: "Organic",
  },
  {
    id: "oh-3",
    name: "Organic India Ashwagandha",
    brand: "Organic India",
    category: "organic-health",
    price: 225,
    mrp: 260,
    image: "https://m.media-amazon.com/images/I/61+t4bF6oIL._SL1000_.jpg",
    weight: "60 Capsules",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 4300,
    badge: "Organic",
  },
  {
    id: "oh-4",
    name: "24 Mantra Organic Jaggery",
    brand: "Organic India",
    category: "organic-health",
    price: 85,
    mrp: 110,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "1 kg",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 3100,
    badge: "Organic",
  },
  {
    id: "oh-5",
    name: "Organic India Quinoa",
    brand: "Organic India",
    category: "organic-health",
    price: 295,
    mrp: 350,
    image: "https://m.media-amazon.com/images/I/61+t4bF6oIL._SL1000_.jpg",
    weight: "500 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 2100,
    badge: "Organic",
  },
  {
    id: "oh-6",
    name: "24 Mantra Organic Turmeric",
    brand: "Organic India",
    category: "organic-health",
    price: 55,
    mrp: 75,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 5800,
    badge: "Organic",
  },
  {
    id: "oh-7",
    name: "Organic India Moringa Powder",
    brand: "Organic India",
    category: "organic-health",
    price: 195,
    mrp: 230,
    image: "https://m.media-amazon.com/images/I/61+t4bF6oIL._SL1000_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 1200,
    badge: "Organic",
  },
  {
    id: "oh-8",
    name: "24 Mantra Organic Brown Sugar",
    brand: "Organic India",
    category: "organic-health",
    price: 95,
    mrp: 120,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "500 g",
    delivery: "10-15 mins",
    rating: 4.3,
    reviews: 1500,
    badge: "Organic",
  },
  {
    id: "oh-9",
    name: "Organic India Triphala",
    brand: "Organic India",
    category: "organic-health",
    price: 185,
    mrp: 210,
    image: "https://m.media-amazon.com/images/I/61+t4bF6oIL._SL1000_.jpg",
    weight: "60 Capsules",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 2300,
    badge: "Organic",
  },
  {
    id: "oh-10",
    name: "24 Mantra Organic Flax Seeds",
    brand: "Organic India",
    category: "organic-health",
    price: 75,
    mrp: 95,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "200 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 900,
    badge: "Organic",
  },

  // ─── Biscuits & Cookies (10 products) ──────────────────────────────────────
  {
    id: "bc-1",
    name: "Parle-G Gold Biscuits",
    brand: "Parle",
    category: "biscuits-cookies",
    price: 10,
    mrp: 10,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.8,
    reviews: 50000,
    badge: "Best Seller",
  },
  {
    id: "bc-2",
    name: "Britannia Good Day Cashew",
    brand: "Britannia",
    category: "biscuits-cookies",
    price: 35,
    mrp: 40,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 25000,
    badge: "Popular",
  },
  {
    id: "bc-3",
    name: "Sunfeast Dark Fantasy Fills",
    brand: "Sunfeast",
    category: "biscuits-cookies",
    price: 45,
    mrp: 50,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "75 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 18000,
    badge: "Best Seller",
  },
  {
    id: "bc-4",
    name: "Oreo Original Chocolate",
    brand: "Oreo",
    category: "biscuits-cookies",
    price: 30,
    mrp: 35,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "120 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 35000,
  },
  {
    id: "bc-5",
    name: "Britannia Marie Gold",
    brand: "Britannia",
    category: "biscuits-cookies",
    price: 30,
    mrp: 35,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "200 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 12000,
  },
  {
    id: "bc-6",
    name: "Parle Hide & Seek Cookies",
    brand: "Parle",
    category: "biscuits-cookies",
    price: 40,
    mrp: 50,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 15000,
    badge: "Popular",
  },
  {
    id: "bc-7",
    name: "Unibic Multigrain Cookies",
    brand: "Unibic",
    category: "biscuits-cookies",
    price: 65,
    mrp: 80,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "150 g",
    delivery: "10-15 mins",
    rating: 4.3,
    reviews: 4200,
  },
  {
    id: "bc-8",
    name: "Britannia NutriChoice",
    brand: "Britannia",
    category: "biscuits-cookies",
    price: 55,
    mrp: 65,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "150 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 9300,
  },
  {
    id: "bc-9",
    name: "Sunfeast Mom's Magic",
    brand: "Sunfeast",
    category: "biscuits-cookies",
    price: 35,
    mrp: 40,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 7800,
  },
  {
    id: "bc-10",
    name: "Parle Monaco Salted",
    brand: "Parle",
    category: "biscuits-cookies",
    price: 25,
    mrp: 30,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "150 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 11000,
  },

  // ─── Noodles & Ready-to-Eat (10 products) ──────────────────────────────────
  {
    id: "nre-1",
    name: "Maggi 2-Minute Masala Noodles",
    brand: "Maggi",
    category: "noodles-ready-to-eat",
    price: 14,
    mrp: 14,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "70 g",
    delivery: "8-12 mins",
    rating: 4.8,
    reviews: 100000,
    badge: "Best Seller",
  },
  {
    id: "nre-2",
    name: "Sunfeast Yippee Magic Masala",
    brand: "Sunfeast",
    category: "noodles-ready-to-eat",
    price: 12,
    mrp: 12,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "70 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 45000,
    badge: "Popular",
  },
  {
    id: "nre-3",
    name: "Ching's Schezwan Noodles",
    brand: "Ching's",
    category: "noodles-ready-to-eat",
    price: 15,
    mrp: 15,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "60 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 21000,
  },
  {
    id: "nre-4",
    name: "MTR Paneer Butter Masala",
    brand: "MTR",
    category: "noodles-ready-to-eat",
    price: 110,
    mrp: 130,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "300 g",
    delivery: "12-18 mins",
    rating: 4.4,
    reviews: 5800,
    badge: "Popular",
  },
  {
    id: "nre-5",
    name: "Maggi Pazzta Cheese Macaroni",
    brand: "Maggi",
    category: "noodles-ready-to-eat",
    price: 25,
    mrp: 28,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "70 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 9200,
  },
  {
    id: "nre-6",
    name: "MTR Poha Instant Mix",
    brand: "MTR",
    category: "noodles-ready-to-eat",
    price: 20,
    mrp: 25,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "60 g",
    delivery: "10-15 mins",
    rating: 4.3,
    reviews: 4100,
  },
  {
    id: "nre-7",
    name: "Ching's Hot Garlic Noodles",
    brand: "Ching's",
    category: "noodles-ready-to-eat",
    price: 15,
    mrp: 15,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "60 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 3200,
  },
  {
    id: "nre-8",
    name: "MTR Ready-to-Eat Dal Makhani",
    brand: "MTR",
    category: "noodles-ready-to-eat",
    price: 105,
    mrp: 120,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "300 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 2900,
  },
  {
    id: "nre-9",
    name: "Maggi Cuppa Noodles Masala",
    brand: "Maggi",
    category: "noodles-ready-to-eat",
    price: 45,
    mrp: 50,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "70 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 12000,
  },
  {
    id: "nre-10",
    name: "Nissin Cup Noodles Manchow",
    brand: "Nissin",
    category: "noodles-ready-to-eat",
    price: 50,
    mrp: 55,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "70 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 8300,
  },

  // ─── Chips & Namkeen (10 products) ─────────────────────────────────────────
  {
    id: "cn-1",
    name: "Haldiram's Aloo Bhujia",
    brand: "Haldiram's",
    category: "chips-namkeen",
    price: 85,
    mrp: 99,
    image: "https://m.media-amazon.com/images/I/81fI9mYp7OL._SL1500_.jpg",
    weight: "200 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 45000,
    badge: "Best Seller",
  },
  {
    id: "cn-2",
    name: "Lay's Classic Salted",
    brand: "Lay's",
    category: "chips-namkeen",
    price: 20,
    mrp: 20,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "50 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 32000,
    badge: "Popular",
  },
  {
    id: "cn-3",
    name: "Kurkure Masala Munch",
    brand: "Kurkure",
    category: "chips-namkeen",
    price: 20,
    mrp: 20,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "75 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 28000,
  },
  {
    id: "cn-4",
    name: "Bingo Mad Angles Achari",
    brand: "Bingo",
    category: "chips-namkeen",
    price: 20,
    mrp: 20,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "60 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 15000,
  },
  {
    id: "cn-5",
    name: "Haldiram's Moong Dal",
    brand: "Haldiram's",
    category: "chips-namkeen",
    price: 45,
    mrp: 50,
    image: "https://m.media-amazon.com/images/I/81fI9mYp7OL._SL1500_.jpg",
    weight: "200 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 12000,
    badge: "Popular",
  },
  {
    id: "cn-6",
    name: "Lay's India's Magic Masala",
    brand: "Lay's",
    category: "chips-namkeen",
    price: 20,
    mrp: 20,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "50 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 18000,
  },
  {
    id: "cn-7",
    name: "Kurkure Green Chutney",
    brand: "Kurkure",
    category: "chips-namkeen",
    price: 20,
    mrp: 20,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "75 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 9500,
  },
  {
    id: "cn-8",
    name: "Haldiram's Navratan Mix",
    brand: "Haldiram's",
    category: "chips-namkeen",
    price: 75,
    mrp: 85,
    image: "https://m.media-amazon.com/images/I/81fI9mYp7OL._SL1500_.jpg",
    weight: "200 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 8400,
  },
  {
    id: "cn-9",
    name: "Bikaji Bikaneri Bhujia",
    brand: "Bikaji",
    category: "chips-namkeen",
    price: 80,
    mrp: 95,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "200 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 5200,
  },
  {
    id: "cn-10",
    name: "Bingo Tedhe Medhe Masala",
    brand: "Bingo",
    category: "chips-namkeen",
    price: 20,
    mrp: 20,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "75 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 11000,
  },

  // ─── Tea & Coffee (10 products) ────────────────────────────────────────────
  {
    id: "tc-1",
    name: "Tata Tea Premium",
    brand: "Tata",
    category: "tea-coffee",
    price: 125,
    mrp: 145,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "250 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 35000,
    badge: "Best Seller",
  },
  {
    id: "tc-2",
    name: "Red Label Tea",
    brand: "Tata",
    category: "tea-coffee",
    price: 135,
    mrp: 155,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "250 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 28000,
    badge: "Popular",
  },
  {
    id: "tc-3",
    name: "Nescafe Classic Coffee",
    brand: "Nescafe",
    category: "tea-coffee",
    price: 195,
    mrp: 220,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 42000,
    badge: "Best Seller",
  },
  {
    id: "tc-4",
    name: "Bru Instant Coffee",
    brand: "Nescafe",
    category: "tea-coffee",
    price: 185,
    mrp: 210,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 15000,
  },
  {
    id: "tc-5",
    name: "Taj Mahal Tea",
    brand: "Tata",
    category: "tea-coffee",
    price: 245,
    mrp: 280,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "250 g",
    delivery: "10-15 mins",
    rating: 4.8,
    reviews: 12000,
    badge: "Popular",
  },
  {
    id: "tc-6",
    name: "Society Tea",
    brand: "Tata",
    category: "tea-coffee",
    price: 115,
    mrp: 130,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "250 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 8300,
  },
  {
    id: "tc-7",
    name: "Nescafe Gold",
    brand: "Nescafe",
    category: "tea-coffee",
    price: 495,
    mrp: 550,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "100 g",
    delivery: "12-18 mins",
    rating: 4.9,
    reviews: 15000,
    badge: "Popular",
  },
  {
    id: "tc-8",
    name: "Tata Tea Gold",
    brand: "Tata",
    category: "tea-coffee",
    price: 155,
    mrp: 180,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "250 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 9200,
  },
  {
    id: "tc-9",
    name: "Wagh Bakri Premium Tea",
    brand: "Tata",
    category: "tea-coffee",
    price: 145,
    mrp: 165,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "250 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 11000,
  },
  {
    id: "tc-10",
    name: "Continental Coffee Xtra",
    brand: "Nescafe",
    category: "tea-coffee",
    price: 165,
    mrp: 195,
    image: "https://m.media-amazon.com/images/I/61qC9H21E0L._SL1000_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 5800,
  },

  // ─── Health Drinks (10 products) ───────────────────────────────────────────
  {
    id: "hd-1",
    name: "Bournvita Health Drink",
    brand: "Bournvita",
    category: "health-drinks",
    price: 345,
    mrp: 399,
    image: "https://m.media-amazon.com/images/I/71+v9h1-E6L._SL1500_.jpg",
    weight: "500 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 45000,
    badge: "Best Seller",
  },
  {
    id: "hd-2",
    name: "Horlicks Classic Malt",
    brand: "Horlicks",
    category: "health-drinks",
    price: 295,
    mrp: 340,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "500 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 38000,
    badge: "Popular",
  },
  {
    id: "hd-3",
    name: "Complan Royale Chocolate",
    brand: "Bournvita",
    category: "health-drinks",
    price: 285,
    mrp: 325,
    image: "https://m.media-amazon.com/images/I/71+v9h1-E6L._SL1500_.jpg",
    weight: "500 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 25000,
  },
  {
    id: "hd-4",
    name: "Boost Health Drink",
    brand: "Horlicks",
    category: "health-drinks",
    price: 265,
    mrp: 310,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "500 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 18000,
  },
  {
    id: "hd-5",
    name: "Horlicks Women's Plus",
    brand: "Horlicks",
    category: "health-drinks",
    price: 375,
    mrp: 425,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "400 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 5200,
    badge: "New",
  },
  {
    id: "hd-6",
    name: "Bournvita 5 Star Magic",
    brand: "Bournvita",
    category: "health-drinks",
    price: 365,
    mrp: 410,
    image: "https://m.media-amazon.com/images/I/71+v9h1-E6L._SL1500_.jpg",
    weight: "500 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 9100,
  },
  {
    id: "hd-7",
    name: "Complan Pista Badam",
    brand: "Bournvita",
    category: "health-drinks",
    price: 295,
    mrp: 340,
    image: "https://m.media-amazon.com/images/I/71+v9h1-E6L._SL1500_.jpg",
    weight: "500 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 3800,
  },
  {
    id: "hd-8",
    name: "Boost 5 Star Magic",
    brand: "Horlicks",
    category: "health-drinks",
    price: 275,
    mrp: 320,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "500 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 2900,
  },
  {
    id: "hd-9",
    name: "Ensure Adult Nutrition",
    brand: "Bournvita",
    category: "health-drinks",
    price: 645,
    mrp: 720,
    image: "https://m.media-amazon.com/images/I/71+v9h1-E6L._SL1500_.jpg",
    weight: "400 g",
    delivery: "12-18 mins",
    rating: 4.8,
    reviews: 4300,
    badge: "Popular",
  },
  {
    id: "hd-10",
    name: "Pediasure Chocolate",
    brand: "Horlicks",
    category: "health-drinks",
    price: 595,
    mrp: 680,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "400 g",
    delivery: "12-18 mins",
    rating: 4.7,
    reviews: 5800,
  },

  // ─── Oats & Breakfast (10 products) ────────────────────────────────────────
  {
    id: "ob-1",
    name: "Saffola Masala Oats Peppy",
    brand: "Saffola",
    category: "oats-breakfast",
    price: 35,
    mrp: 40,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "40 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 15000,
    badge: "Best Seller",
  },
  {
    id: "ob-2",
    name: "Quaker Oats Multi Grain",
    brand: "Quaker",
    category: "oats-breakfast",
    price: 210,
    mrp: 245,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "1 kg",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 12000,
    badge: "Popular",
  },
  {
    id: "ob-3",
    name: "Kellogg's Oats",
    brand: "Kellogg's",
    category: "oats-breakfast",
    price: 175,
    mrp: 210,
    image: "https://m.media-amazon.com/images/I/71+v9h1-E6L._SL1500_.jpg",
    weight: "1 kg",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 9500,
  },
  {
    id: "ob-4",
    name: "Saffola Oats Classic Masala",
    brand: "Saffola",
    category: "oats-breakfast",
    price: 35,
    mrp: 40,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "40 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 8200,
  },
  {
    id: "ob-5",
    name: "Quaker Oats Lemony Veggie",
    brand: "Quaker",
    category: "oats-breakfast",
    price: 45,
    mrp: 50,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "40 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 3200,
  },
  {
    id: "ob-6",
    name: "Yoga Bar Muesli",
    brand: "Tata",
    category: "oats-breakfast",
    price: 345,
    mrp: 400,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "500 g",
    delivery: "12-18 mins",
    rating: 4.6,
    reviews: 4100,
    badge: "Popular",
  },
  {
    id: "ob-7",
    name: "True Elements Rolled Oats",
    brand: "Organic India",
    category: "oats-breakfast",
    price: 275,
    mrp: 320,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "1 kg",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 1800,
    badge: "Organic",
  },
  {
    id: "ob-8",
    name: "Saffola Oats Veggie Twist",
    brand: "Saffola",
    category: "oats-breakfast",
    price: 35,
    mrp: 40,
    image: "https://m.media-amazon.com/images/I/71-6R6Vp-RL._SL1500_.jpg",
    weight: "40 g",
    delivery: "10-15 mins",
    rating: 4.4,
    reviews: 5200,
  },
  {
    id: "ob-9",
    name: "MuscleBlaze High Protein",
    brand: "Tata",
    category: "oats-breakfast",
    price: 450,
    mrp: 520,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "1 kg",
    delivery: "12-18 mins",
    rating: 4.7,
    reviews: 2900,
  },
  {
    id: "ob-10",
    name: "Baggry's Steel Cut Oats",
    brand: "Baggry's",
    category: "oats-breakfast",
    price: 245,
    mrp: 290,
    image: "https://m.media-amazon.com/images/I/71+6yZz7-iL._SL1500_.jpg",
    weight: "1 kg",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 1200,
  },

  // ─── Home Cleaning (10 products) ───────────────────────────────────────────
  {
    id: "hc-1",
    name: "Surf Excel Matic Top Load",
    brand: "Surf Excel",
    category: "home-cleaning",
    price: 495,
    mrp: 580,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "2 kg",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 35000,
    badge: "Best Seller",
  },
  {
    id: "hc-2",
    name: "Ariel Matic Front Load",
    brand: "Surf Excel",
    category: "home-cleaning",
    price: 525,
    mrp: 610,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "2 kg",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 28000,
    badge: "Popular",
  },
  {
    id: "hc-3",
    name: "Vim Dishwash Bar",
    brand: "Surf Excel",
    category: "home-cleaning",
    price: 30,
    mrp: 35,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "300 g",
    delivery: "10-15 mins",
    rating: 4.8,
    reviews: 50000,
    badge: "Best Seller",
  },
  {
    id: "hc-4",
    name: "Lizol Disinfectant Cleaner",
    brand: "Dettol",
    category: "home-cleaning",
    price: 185,
    mrp: 210,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "975 ml",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 15000,
  },
  {
    id: "hc-5",
    name: "Harpic Toilet Cleaner",
    brand: "Dettol",
    category: "home-cleaning",
    price: 165,
    mrp: 190,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "1 L",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 21000,
    badge: "Best Seller",
  },
  {
    id: "hc-6",
    name: "Comfort Fabric Conditioner",
    brand: "Surf Excel",
    category: "home-cleaning",
    price: 210,
    mrp: 245,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "860 ml",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 9300,
  },
  {
    id: "hc-7",
    name: "Dettol Liquid Disinfectant",
    brand: "Dettol",
    category: "home-cleaning",
    price: 185,
    mrp: 210,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "500 ml",
    delivery: "10-15 mins",
    rating: 4.8,
    reviews: 35000,
    badge: "Popular",
  },
  {
    id: "hc-8",
    name: "Colin Glass Cleaner",
    brand: "Dettol",
    category: "home-cleaning",
    price: 95,
    mrp: 110,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "500 ml",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 8200,
  },
  {
    id: "hc-9",
    name: "Exo Dishwash Bar",
    brand: "Fortune",
    category: "home-cleaning",
    price: 25,
    mrp: 30,
    image: "https://m.media-amazon.com/images/I/81VfS2u9LGL._SL1500_.jpg",
    weight: "250 g",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 5800,
  },
  {
    id: "hc-10",
    name: "Rin Detergent Bar",
    brand: "Surf Excel",
    category: "home-cleaning",
    price: 15,
    mrp: 18,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "250 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 11000,
  },

  // ─── Personal Care (10 products) ───────────────────────────────────────────
  {
    id: "pc-1",
    name: "Colgate Strong Teeth",
    brand: "Colgate",
    category: "personal-care",
    price: 95,
    mrp: 110,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "200 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 45000,
    badge: "Best Seller",
  },
  {
    id: "pc-2",
    name: "Pepsodent Germicheck",
    brand: "Pepsodent",
    category: "personal-care",
    price: 85,
    mrp: 100,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "150 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 12000,
    badge: "Popular",
  },
  {
    id: "pc-3",
    name: "Dettol Original Soap",
    brand: "Dettol",
    category: "personal-care",
    price: 145,
    mrp: 165,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "4x125 g",
    delivery: "10-15 mins",
    rating: 4.8,
    reviews: 50000,
    badge: "Best Seller",
  },
  {
    id: "pc-4",
    name: "Lifebuoy Total 10 Soap",
    brand: "Dettol",
    category: "personal-care",
    price: 135,
    mrp: 155,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "4x125 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 32000,
  },
  {
    id: "pc-5",
    name: "Dove Cream Beauty Bar",
    brand: "Dettol",
    category: "personal-care",
    price: 185,
    mrp: 220,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "3x125 g",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 25000,
    badge: "Popular",
  },
  {
    id: "pc-6",
    name: "Pantene Hairfall Control",
    brand: "Dettol",
    category: "personal-care",
    price: 245,
    mrp: 290,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "340 ml",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 18000,
  },
  {
    id: "pc-7",
    name: "Head & Shoulders Shampoo",
    brand: "Dettol",
    category: "personal-care",
    price: 265,
    mrp: 310,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "340 ml",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 21000,
    badge: "Popular",
  },
  {
    id: "pc-8",
    name: "Parachute Coconut Hair Oil",
    brand: "Fortune",
    category: "personal-care",
    price: 110,
    mrp: 135,
    image: "https://m.media-amazon.com/images/I/71o1p9fV1BL._SL1500_.jpg",
    weight: "500 ml",
    delivery: "10-15 mins",
    rating: 4.7,
    reviews: 35000,
    badge: "Best Seller",
  },
  {
    id: "pc-9",
    name: "Nivea Soft Cream",
    brand: "Dettol",
    category: "personal-care",
    price: 175,
    mrp: 210,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "200 ml",
    delivery: "10-15 mins",
    rating: 4.5,
    reviews: 12000,
  },
  {
    id: "pc-10",
    name: "Pond's Face Wash",
    brand: "Dettol",
    category: "personal-care",
    price: 145,
    mrp: 180,
    image: "https://m.media-amazon.com/images/I/61kYy5yR6yL._SL1500_.jpg",
    weight: "100 g",
    delivery: "10-15 mins",
    rating: 4.6,
    reviews: 9500,
  },
];

export const getDiscountPercent = (price: number, mrp: number) => {
  if (!mrp || mrp <= price) return 0;
  return Math.round(((mrp - price) / mrp) * 100);
};
